#####
## exp-id conf
#####

###
# PRE
###

[pre_config_clm]

###
# SIM
###
[sim_config_general]
lreal=false
domain_size_str=${CASE_ID:17:4}
domain_size=$(echo "$domain_size_str" | sed 's/^0*//') #$((10#$domain_size_str))

[sim_config_icon]
icon_numioprocs=1
domainfile_icon=static/torus_grid_x${domain_size_str}_y${domain_size_str}_e2000m.nc
icon_mapfile_lbc=map_file.lbc

[sim_config_clm]
domainfile_clm=domain_${domain_size_str}x${domain_size_str}_e2000.nc
surffile_clm=surfdata_${domain_size_str}x${domain_size_str}_e2000_${CASE_ID:0:11}.nc
topofile_clm=topodata_0.9x1.25_zeroed.nc
clmoutvar='TWS','H2OSOI','TSOI','TG','EFLX_LH_TOT','FSH','FSA','FSR','FIRA','Rnet','EFLX_SOIL_GRND'
fini_clm=" "
clm_frc_dir=${geo_dir}/eclm/forcing/${domain_size_str}x${domain_size_str}

[sim_config_parflow]
pfl_ngx=${domain_size}
pfl_ngy=${domain_size}
fini_pfl=${geo_dir}/parflow/init/rur_ic_press_${domain_size_str}x${domain_size_str}_${CASE_ID:6:5}_${CASE_ID:12:4}.pfb

[sim_config_oas]
icon_ncg=$((${domain_size} * ${domain_size} * 2))
clm_ngx=$((${domain_size} * ${domain_size} * 2))
clm_ngy=1
geo_dir_oas=${geo_dir}/oasis/static/${domain_size_str}x${domain_size_str}/

###
# POS
###


###
# VIS
###
